project_id = "qltfylleiwjvtngmsdyg"

[functions.fal-image-generation]
verify_jwt = false

[functions.fal-video-generation]
verify_jwt = false

[functions.generate-image-gemini]
verify_jwt = true

[functions.create-beta-subscription]
verify_jwt = true

[functions.analyze-competitor-sentiment]
verify_jwt = true